# =========================================================
# UnBiased Trades — AUTO SIGNAL GENERATOR
# QQQ ONLY / PAPER TEST SIGNAL DRIVER
# =========================================================

import os
import json
import time
from datetime import datetime, timezone

SIGNAL_FILE = os.getenv("SIGNAL_FILE", "ai_signal.json").strip()
MARKET_FILE = os.getenv("MARKET_DATA_FILE", "market_prices.json").strip()
STATE_FILE = "auto_signal_generator_state.json"

ENABLE_AUTO_SIGNAL_GENERATOR = os.getenv("ENABLE_AUTO_SIGNAL_GENERATOR", "true").lower() == "true"
AUTO_SIGNAL_COOLDOWN_SECONDS = int(os.getenv("AUTO_SIGNAL_COOLDOWN_SECONDS", "300"))

# HARD LOCK — DO NOT USE SPY
TICKER = "QQQ"

DIRECTION = os.getenv("AUTO_SIGNAL_DIRECTION", "CALL").upper().strip()
if DIRECTION not in {"CALL", "PUT"}:
    DIRECTION = "CALL"


def load_json(path, default):
    try:
        if not os.path.exists(path):
            return default
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default


def save_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def now_ts():
    return int(time.time())


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def get_qqq_price():
    data = load_json(MARKET_FILE, {})

    qqq = data.get("QQQ")
    if isinstance(qqq, dict):
        price = qqq.get("price") or qqq.get("last") or qqq.get("close")
        try:
            price = float(price)
            if price > 100:
                return price
        except Exception:
            pass

    price = data.get("price")
    try:
        price = float(price)
        if price > 100:
            return price
    except Exception:
        pass

    return None


def cooldown_ready(force=False):
    if force:
        return True

    state = load_json(STATE_FILE, {})
    last_signal_ts = int(state.get("last_signal_ts", 0) or 0)

    if last_signal_ts <= 0:
        return True

    return now_ts() - last_signal_ts >= AUTO_SIGNAL_COOLDOWN_SECONDS


def build_signal(price):
    price = round(float(price), 2)

    if DIRECTION == "CALL":
        stop = round(price - 1.50, 2)
        targets = [round(price + 1.50, 2), round(price + 3.00, 2)]
    else:
        stop = round(price + 1.50, 2)
        targets = [round(price - 1.50, 2), round(price - 3.00, 2)]

    return {
        "ticker": "QQQ",
        "symbol": "QQQ",
        "underlying": "QQQ",

        "direction": DIRECTION,
        "side": DIRECTION,

        "entry": price,
        "entry_price": price,
        "stop": stop,
        "stop_loss": stop,
        "targets": targets,
        "target": targets[0],

        "confidence": "B",
        "grade": "B",

        "setup": "AUTO_QQQ_PAPER_TEST",
        "setup_type": "auto_signal_generator",
        "trigger": "fresh_auto_generated_qqq_signal",

        "session": "auto",
        "time_window": "paper_test",
        "trade_reason": "Fresh QQQ-only paper test signal generated by auto_signal_generator.py",

        "timestamp": now_ts(),
        "created_at": now_iso(),
        "source": "auto_signal_generator",

        "force_execution": True,
        "paper_only": True
    }


def generate_signal(force=False):
    print("[AUTO SIGNAL DEBUG] generator loaded | hard_locked_ticker=QQQ", flush=True)

    if not ENABLE_AUTO_SIGNAL_GENERATOR:
        print("[AUTO SIGNAL] disabled", flush=True)
        return None

    if not cooldown_ready(force=force):
        print("[AUTO SIGNAL] cooldown active", flush=True)
        return None

    price = get_qqq_price()

    if price is None:
        print("[AUTO SIGNAL] skipped: no valid QQQ price", flush=True)
        return None

    signal = build_signal(price)

    save_json(SIGNAL_FILE, signal)

    save_json(STATE_FILE, {
        "last_signal_ts": now_ts(),
        "last_ticker": "QQQ",
        "last_direction": DIRECTION,
        "last_entry": signal["entry"],
        "last_signal_file": SIGNAL_FILE,
    })

    print(
        f"[AUTO SIGNAL] Generated QQQ {DIRECTION} "
        f"entry={signal['entry']} stop={signal['stop']} targets={signal['targets']}",
        flush=True,
    )

    return signal


if __name__ == "__main__":
    result = generate_signal(force=True)
    if result:
        print(json.dumps(result, indent=2))
    else:
        print("No signal generated")
